name: Linter - Flake8

on: [pull_request, workflow_dispatch]

jobs:
  # Linter
  flake8:
    name: Flake8
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setting up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-preview: true
          poetry-version: "1.6.1"

      - name: Install Dependencies
        run: |
          make init

      - name: Setup flake8 Annotations
        uses: rbialon/flake8-annotations@v1

      - name: Run flake8
        run: make flake8